# Generated by Django 4.2.3 on 2023-07-27 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.TimeField(verbose_name='Время рассылки')),
                ('frequency', models.CharField(choices=[('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], max_length=10, verbose_name='Периодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена')], max_length=10, verbose_name='Статус рассылки')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержимое письма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latter.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='SmsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тема письма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latter.client', verbose_name='Клиент')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='latter.mailing', verbose_name='Сообщение для рассылки')),
            ],
            options={
                'verbose_name': 'Смс рассылка',
                'verbose_name_plural': 'Смс рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время последней попытки')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Неудачно')], max_length=10, verbose_name='Статус попытки')),
                ('server_response', models.TextField(verbose_name='Ответ почтового сервера, если он был')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='latter.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
