# Generated by Django 4.2.3 on 2023-07-27 06:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='send_time',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='status',
        ),
        migrations.AddField(
            model_name='mailing',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема письма'),
        ),
        migrations.AddField(
            model_name='smsletter',
            name='frequency',
            field=models.CharField(choices=[('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], default='', max_length=10, verbose_name='Периодичность'),
        ),
        migrations.AddField(
            model_name='smsletter',
            name='send_time',
            field=models.TimeField(default=datetime.datetime(2023, 7, 27, 6, 23, 22, 248626, tzinfo=datetime.timezone.utc), verbose_name='Время рассылки'),
        ),
        migrations.AddField(
            model_name='smsletter',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('started', 'Запущена'), ('finished', 'Завершена')], default='created', max_length=10, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='smsletter',
            name='message',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Сообщение для рассылки'),
        ),
        migrations.AlterField(
            model_name='smsletter',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='latter.mailing', verbose_name='Тема письма'),
        ),
    ]
